//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteLoja.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarrinhoCompraIten
    {
        public int IDCarrinhoCompraItem { get; set; }
        public Nullable<int> IDProduto { get; set; }
        public int Quantidade { get; set; }
        public string IDCarrinhoCompra { get; set; }
    
        public virtual Produto Produto { get; set; }
    }
}
