//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteLoja.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produto()
        {
            this.CarrinhoCompraItens = new HashSet<CarrinhoCompraIten>();
        }
    
        public int ID { get; set; }
        public int IDCategoia { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public decimal Preco { get; set; }
        public string ImagemUrl { get; set; }
        public string ImagemThumbnaiUrl { get; set; }
        public bool RoupaDaSemana { get; set; }
        public bool EmEstoque { get; set; }
        public Nullable<decimal> PrecoAtual { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarrinhoCompraIten> CarrinhoCompraItens { get; set; }
        public virtual Categoria Categoria { get; set; }
    }
}
